### ISSUE TITLE
Methodology Questions

### ISSUE THREAD

**Issue by patwater** [bayesimpact/water#3]
What are you using to assign a budget to each agency?  Also how did you come upon the following growth definition?

            growth = usage[matching_keys[-1]] / usage[matching_keys[-2]]
            result = usage[matching_keys[-1]] * growth

**Comment by everett-wetchler** [comment]
Hey Pat, to your questions:

1. The budget is computed based on the conservation standard (a percentage like 15%) and the reference point, which is the 2013 total potable water consumption per capita. I can point you to the columns and places in the code where this is done if you like.
2. We are using a crude predictive methodology -- keep in mind that this is a proof of concept! We tinkered with a few more complicated models but the dataset was too small to produce meaningful predictions with reasonable error. We found this "linear model" to work well for the sake of this demo, and it's simple to compute and follow, so we stuck with it.
   * Since the code is admittedly little annoying to parse, I'll describe it in words -- basically, if water usage last January was 100, and this January was 110 (10% growth), we will predict next January to also grow by 10% (to 121 in this case). In the above code, the `growth` variable would be 1.1 and the `result` would be 121.

**Comment by patwater** [comment]
Thanks for taking the time to respond Everett!  Note regarding 1 a water budget is actually a term of art in the California water industry and the 2013 R-GPCD based compliance framework != a water budget.  See https://www.mnwd.com/understandingwaterbudget/  Note the Governor's new long term conservation framework from May 2016 involves setting a water budget for every major urban water supplier in the state.  

Regarding 2, check out the Pacific Institute's report on demand forecasting: http://pacinst.org/rethinking-future-water-demand-blog/   You can also see some of our work to forecast water demand on a short term basis with DataKind here: https://github.com/California-Data-Collaborative/waterd 

Thanks for the plain language deconstruction of the code btw :)
